# Simulation settings for using moveit_sim_controllers with gripper
moveit_sim_hw_interface:
  joint_model_group: dual_arm
  joint_model_group_pose: all_zero
controller_list:
  - name: fake_mp_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6 
  - name: fake_mp_m_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1_m
      - joint_2_m
      - joint_3_m
      - joint_4_m
      - joint_5_m
      - joint_6_m
      - gripper_joint_m
      - gripper_tcp_joint_m
  - name: fake_dual_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3 
      - joint_4
      - joint_5 
      - joint_6 
      - joint_1_m
      - joint_2_m 
      - joint_3_m 
      - joint_4_m 
      - joint_5_m 
      - joint_6_m
      - gripper_joint_m
      - gripper_base_joint_m
      - gripper_tcp_joint_m
initial:  # Define initial robot poses per group
  - group: mp
    pose: ready
  - group: mp_m
    pose: ready
  - group: dual_arm
    pose: ready